import type { Metadata } from "next";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "@/app/globals.css";



export const metadata: Metadata = {
  title: "Hamita Wedding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
      
      >
         <AntdRegistry> {children}</AntdRegistry>
       
      </body>
    </html>
  );
}
